use inputbot::{KeybdKey, MouseButton};

pub fn string_to_key(s: &str) -> Option<KeybdKey> {
    match s {
        "BS" => Some(KeybdKey::BackspaceKey),
        "TB" => Some(KeybdKey::TabKey),
        "EN" => Some(KeybdKey::EnterKey),
        "ES" => Some(KeybdKey::EscapeKey),
        "SP" => Some(KeybdKey::SpaceKey),
        "PU" => Some(KeybdKey::PageUpKey),
        "PD" => Some(KeybdKey::PageDownKey),
        "ED" => Some(KeybdKey::EndKey),
        "HM" => Some(KeybdKey::HomeKey),
        "UA" => Some(KeybdKey::UpKey),
        "DA" => Some(KeybdKey::DownKey),
        "IN" => Some(KeybdKey::InsertKey),
        "DL" => Some(KeybdKey::DeleteKey),

        "0" => Some(KeybdKey::Numrow0Key),
        "1" => Some(KeybdKey::Numrow1Key),
        "2" => Some(KeybdKey::Numrow2Key),
        "3" => Some(KeybdKey::Numrow3Key),
        "4" => Some(KeybdKey::Numrow4Key),
        "5" => Some(KeybdKey::Numrow5Key),
        "6" => Some(KeybdKey::Numrow6Key),
        "7" => Some(KeybdKey::Numrow7Key),
        "8" => Some(KeybdKey::Numrow8Key),
        "9" => Some(KeybdKey::Numrow9Key),

        "A" => Some(KeybdKey::AKey),
        "B" => Some(KeybdKey::BKey),
        "C" => Some(KeybdKey::CKey),
        "D" => Some(KeybdKey::DKey),
        "E" => Some(KeybdKey::EKey),
        "F" => Some(KeybdKey::FKey),
        "G" => Some(KeybdKey::GKey),
        "H" => Some(KeybdKey::HKey),
        "I" => Some(KeybdKey::IKey),
        "J" => Some(KeybdKey::JKey),
        "K" => Some(KeybdKey::KKey),
        "L" => Some(KeybdKey::LKey),
        "M" => Some(KeybdKey::MKey),
        "N" => Some(KeybdKey::NKey),
        "O" => Some(KeybdKey::OKey),
        "P" => Some(KeybdKey::PKey),
        "Q" => Some(KeybdKey::QKey),
        "R" => Some(KeybdKey::RKey),
        "S" => Some(KeybdKey::SKey),
        "T" => Some(KeybdKey::TKey),
        "U" => Some(KeybdKey::UKey),
        "V" => Some(KeybdKey::VKey),
        "W" => Some(KeybdKey::WKey),
        "X" => Some(KeybdKey::XKey),
        "Y" => Some(KeybdKey::YKey),
        "Z" => Some(KeybdKey::ZKey),

        "LW" => Some(KeybdKey::LSuper),
        "RW" => Some(KeybdKey::RSuper),

        "N0" => Some(KeybdKey::Numpad0Key),
        "N1" => Some(KeybdKey::Numpad1Key),
        "N2" => Some(KeybdKey::Numpad2Key),
        "N3" => Some(KeybdKey::Numpad3Key),
        "N4" => Some(KeybdKey::Numpad4Key),
        "N5" => Some(KeybdKey::Numpad5Key),
        "N6" => Some(KeybdKey::Numpad6Key),
        "N7" => Some(KeybdKey::Numpad7Key),
        "N8" => Some(KeybdKey::Numpad8Key),
        "N9" => Some(KeybdKey::Numpad9Key),

        "F1" => Some(KeybdKey::F1Key),
        "F2" => Some(KeybdKey::F2Key),
        "F3" => Some(KeybdKey::F3Key),
        "F4" => Some(KeybdKey::F4Key),
        "F5" => Some(KeybdKey::F5Key),
        "F6" => Some(KeybdKey::F6Key),
        "F7" => Some(KeybdKey::F7Key),
        "F8" => Some(KeybdKey::F8Key),
        "F9" => Some(KeybdKey::F9Key),
        "10" => Some(KeybdKey::F10Key),
        "11" => Some(KeybdKey::F11Key),
        "12" => Some(KeybdKey::F12Key),
        "13" => Some(KeybdKey::F13Key),
        "14" => Some(KeybdKey::F14Key),
        "15" => Some(KeybdKey::F15Key),
        "16" => Some(KeybdKey::F16Key),
        "17" => Some(KeybdKey::F17Key),
        "18" => Some(KeybdKey::F18Key),
        "19" => Some(KeybdKey::F19Key),
        "20" => Some(KeybdKey::F20Key),
        "21" => Some(KeybdKey::F21Key),
        "22" => Some(KeybdKey::F22Key),
        "23" => Some(KeybdKey::F23Key),
        "24" => Some(KeybdKey::F24Key),

        "NL" => Some(KeybdKey::NumLockKey),
        "SL" => Some(KeybdKey::ScrollLockKey),
        "CL" => Some(KeybdKey::CapsLockKey),

        "LS" => Some(KeybdKey::LShiftKey),
        "RS" => Some(KeybdKey::RShiftKey),
        "LC" => Some(KeybdKey::LControlKey),
        "RC" => Some(KeybdKey::RControlKey),

        "BB" => Some(KeybdKey::BrowserBackKey),
        "BF" => Some(KeybdKey::BrowserForwardKey),
        "BR" => Some(KeybdKey::BrowserRefreshKey),

        "VM" => Some(KeybdKey::VolumeMuteKey),
        "V-" => Some(KeybdKey::VolumeDownKey),
        "V+" => Some(KeybdKey::VolumeUpKey),

        "M>" => Some(KeybdKey::MediaNextTrackKey),
        "M<" => Some(KeybdKey::MediaPrevTrackKey),
        "M■" => Some(KeybdKey::MediaStopKey),
        "M▶" => Some(KeybdKey::MediaPlayPauseKey),

        "`" => Some(KeybdKey::BackquoteKey),
        "/" => Some(KeybdKey::SlashKey),
        "\\" => Some(KeybdKey::BackslashKey),
        "," => Some(KeybdKey::CommaKey),
        "." => Some(KeybdKey::PeriodKey),
        "-" => Some(KeybdKey::MinusKey),
        "'" => Some(KeybdKey::QuoteKey),
        ";" => Some(KeybdKey::SemicolonKey),
        "[" => Some(KeybdKey::LBracketKey),
        "]" => Some(KeybdKey::RBracketKey),
        "=" => Some(KeybdKey::EqualKey),

        _ => None,
    }
}

pub fn string_to_mouse(s: &str) -> Option<MouseButton> {
    match s {
        "LM" => Some(MouseButton::LeftButton),
        "MM" => Some(MouseButton::MiddleButton),
        "RM" => Some(MouseButton::RightButton),
        _ => None,
    }
}
