use inputbot::KeybdKey;

pub fn key_to_string(key: &KeybdKey) -> &'static str {
    match key {
        KeybdKey::BackspaceKey => "BS",
        KeybdKey::TabKey => "TB",
        KeybdKey::EnterKey => "EN",
        KeybdKey::EscapeKey => "ES",
        KeybdKey::SpaceKey => "SP",
        KeybdKey::PageUpKey => "PU",
        KeybdKey::PageDownKey => "PD",
        KeybdKey::EndKey => "ED",
        KeybdKey::HomeKey => "HM",
        KeybdKey::LeftKey => "LA",
        KeybdKey::UpKey => "UA",
        KeybdKey::RightKey => "RA",
        KeybdKey::DownKey => "DA",
        KeybdKey::InsertKey => "IN",
        KeybdKey::DeleteKey => "DL",

        KeybdKey::Numrow0Key => "0",
        KeybdKey::Numrow1Key => "1",
        KeybdKey::Numrow2Key => "2",
        KeybdKey::Numrow3Key => "3",
        KeybdKey::Numrow4Key => "4",
        KeybdKey::Numrow5Key => "5",
        KeybdKey::Numrow6Key => "6",
        KeybdKey::Numrow7Key => "7",
        KeybdKey::Numrow8Key => "8",
        KeybdKey::Numrow9Key => "9",

        KeybdKey::AKey => "A",
        KeybdKey::BKey => "B",
        KeybdKey::CKey => "C",
        KeybdKey::DKey => "D",
        KeybdKey::EKey => "E",
        KeybdKey::FKey => "F",
        KeybdKey::GKey => "G",
        KeybdKey::HKey => "H",
        KeybdKey::IKey => "I",
        KeybdKey::JKey => "J",
        KeybdKey::KKey => "K",
        KeybdKey::LKey => "L",
        KeybdKey::MKey => "M",
        KeybdKey::NKey => "N",
        KeybdKey::OKey => "O",
        KeybdKey::PKey => "P",
        KeybdKey::QKey => "Q",
        KeybdKey::RKey => "R",
        KeybdKey::SKey => "S",
        KeybdKey::TKey => "T",
        KeybdKey::UKey => "U",
        KeybdKey::VKey => "V",
        KeybdKey::WKey => "W",
        KeybdKey::XKey => "X",
        KeybdKey::YKey => "Y",
        KeybdKey::ZKey => "Z",

        KeybdKey::LSuper => "LW",
        KeybdKey::RSuper => "RW",

        KeybdKey::Numpad0Key => "N0",
        KeybdKey::Numpad1Key => "N1",
        KeybdKey::Numpad2Key => "N2",
        KeybdKey::Numpad3Key => "N3",
        KeybdKey::Numpad4Key => "N4",
        KeybdKey::Numpad5Key => "N5",
        KeybdKey::Numpad6Key => "N6",
        KeybdKey::Numpad7Key => "N7",
        KeybdKey::Numpad8Key => "N8",
        KeybdKey::Numpad9Key => "N9",

        KeybdKey::F1Key => "F1",
        KeybdKey::F2Key => "F2",
        KeybdKey::F3Key => "F3",
        KeybdKey::F4Key => "F4",
        KeybdKey::F5Key => "F5",
        KeybdKey::F6Key => "F6",
        KeybdKey::F7Key => "F7",
        KeybdKey::F8Key => "F8",
        KeybdKey::F9Key => "F9",
        KeybdKey::F10Key => "10",
        KeybdKey::F11Key => "11",
        KeybdKey::F12Key => "12",
        KeybdKey::F13Key => "13",
        KeybdKey::F14Key => "14",
        KeybdKey::F15Key => "15",
        KeybdKey::F16Key => "16",
        KeybdKey::F17Key => "17",
        KeybdKey::F18Key => "18",
        KeybdKey::F19Key => "19",
        KeybdKey::F20Key => "20",
        KeybdKey::F21Key => "21",
        KeybdKey::F22Key => "22",
        KeybdKey::F23Key => "23",
        KeybdKey::F24Key => "24",

        KeybdKey::NumLockKey => "NL",
        KeybdKey::ScrollLockKey => "SL",
        KeybdKey::CapsLockKey => "CL",

        KeybdKey::LShiftKey => "LS",
        KeybdKey::RShiftKey => "RS",
        KeybdKey::LControlKey => "LC",
        KeybdKey::RControlKey => "RC",
        KeybdKey::LAltKey => "LA",
        KeybdKey::RAltKey => "RA",

        KeybdKey::BrowserBackKey => "BB",
        KeybdKey::BrowserForwardKey => "BF",
        KeybdKey::BrowserRefreshKey => "BR",

        KeybdKey::VolumeMuteKey => "VM",
        KeybdKey::VolumeDownKey => "V-",
        KeybdKey::VolumeUpKey => "V+",

        KeybdKey::MediaNextTrackKey => "M>",
        KeybdKey::MediaPrevTrackKey => "M<",
        KeybdKey::MediaStopKey => "M■",
        KeybdKey::MediaPlayPauseKey => "M▶",

        KeybdKey::BackquoteKey => "`",
        KeybdKey::SlashKey => "/",
        KeybdKey::BackslashKey => "\\",
        KeybdKey::CommaKey => ",",
        KeybdKey::PeriodKey => ".",
        KeybdKey::MinusKey => "-",
        KeybdKey::QuoteKey => "'",
        KeybdKey::SemicolonKey => ";",
        KeybdKey::LBracketKey => "[",
        KeybdKey::RBracketKey => "]",
        KeybdKey::EqualKey => "=",

        KeybdKey::OtherKey(_) => "??",
    }
}
